### ISSUE TITLE
Delphi Beginner

### ISSUE THREAD

**Issue by kg117** [ric355/ultibocapacitivetouch#1]
@ric355 I have installed Embarcadero® Delphi 10.4 Version 27.0.40680.4203 as I wish to compile and experiment with your ultibocapacitivetouch code. I have also purchased a [](https://www.buydisplay.com/7-hdmi-lcd-module-display-touchscreen-vga-video-driver-board) part number ER-TFTV070-3 which uses a GT911 and a HX6518.
I have never used the Delphi system before. I would much appreciate your guidance as to how to setup and build your code. I would be most grateful for your advice.
Kevin

**Comment by ric355** [comment]
This is an Ultibo device driver. It won't work with Delphi.
You need the Ultibo version of Lazarus to build and use it. It is only for the Ultibo Raspberry Pi bare metal targets.

**Comment by kg117** [comment]
Perhaps this solution will....[https://forums.parallax.com/discussion/173088/connecting-p2-to-the-rpi0-ultibo/p1?new=1](https://forums.parallax.com/discussion/173088/connecting-p2-to-the-rpi0-ultibo/p1?new=1)
